### ISSUE TITLE
readline-type support in the menu bar

### ISSUE THREAD

**Issue by cmcaine** [letoram/durden#58]
It would be nice to use the binds I'm used to from readline/ZLE to edit the input to the menu bar.

E.g. up or c-p to get previous menu invocations. c-u to empty the line, etc.

It feels like a potentially nice interface, but I found it too slow and cumbersome when I wanted to quickly change a bunch of settings to do with the terminal, for example.

In general, I prefer configuring my applications from plaintext files rather than databases (easy to see all non-default options, version control, can use favoured editor, etc), so maybe this whole config setup isn't for me :/

**Comment by letoram** [comment]
you have multiple options of using the menu interface (which is intended for runtime/dynamic binding to UI elements and exploration, it's not a static config system).
0. most static options are exposed as the config.lua file on start, since the values are cached in the database, you need arcan_db drop_appl durden to reset the cache.
1. arcan_db as a command-line tool, arcan_db show_appl durden, arcan_db add_appl_kv durden key value to update, global/system/reset to rebuild and activate. 
2. global/config/system/control=name and you can either mount 'name' as a file system (durden/ipc/name) and have the menu tree as, well, a file system with the arcan-cfgfs FUSE tool, or socat into it, and a set of EXEC / LS / CD / ... commands to manipulate it that way.
3. devmaps/schemes -> sets of config options to apply in one atomic batch.

**Comment by cmcaine** [comment]
Thanks for the pointers. I'll try those out.

I think I'd still like some line editing binds for the menu, so I'll leave the issue open. Obviously feel free to close if you're not interested.

**Comment by letoram** [comment]
there's been talks of those in the past, think it was @cipharius - the input state machine itself is, and will, be reused elsewhere so there's point to doing it even if not for this menu system, a debug console in safespaces and the 'console' WM comes to mind. If you are bored enough - https://github.com/letoram/durden/blob/master/durden/suppl.lua#L1052 is where it all goes down.

**Comment by cmcaine** [comment]
Thanks for the link. I probably don't have time (am procrastinating with this as it is).

At the mo I can't get durden to nest firefox (or even xterm) properly in Xarcan and arcan-wayland wasn't built for some reason and I don't think I can justify spending the time I have on it already, let alone the additional time to add readline-type support ;)
