### ISSUE TITLE
running arcan/debian for the first time

### ISSUE THREAD

**Issue by deb75** [letoram/durden#62]
Hi,

First run of `arcan/durden` ... couples of questions : 
- how do you set the keyboard layout to "azerty" ? Currently it is by default qwerty
- is it possible to apply some color theme, e.g. solarized, to the terminal ?
- the touchscreen works but with some offset and upon single finger movement, the pointer moves faster. How can I improve this ? (my PC is a surface book 2)

Regards

deb75

**Comment by letoram** [comment]
keyboard: (we covered on IRC).
colors:
    statically: (menu) global/settings/terminal/palette=... 
    dynamically: (filesystem:devmaps/colorschemes/something.lua) -> (menu) target/video/color/scheme

touchscreen:
    if the touchscreen is running with the relative mouse classifier it will be offset if that's what you mean, see (filesystem:devmaps/touch/*)

**Comment by deb75** [comment]
Hi

For the keyboard, I set this  in my `.bashrc` : 
```
export XKB_DEFAULT_MODEL=pc105
export XKB_DEFAULT_LAYOUT=fr
export XKB_DEFAULT_VARIANT=oss
```

then I log to the console and start `arcan ~/durden/durden`, but still the keyboard is 'us'

**Comment by letoram** [comment]
interesting, if you run something like arcan-wayland -exec weston-terminal (assuming that is installed) -- will that window have the correct layout?

**Comment by letoram** [comment]
Ok I know what's going on. XKB common uses the secure_getenv which will fail if the binary is suid even if we have dropped all privileges at the point of invocation. This needed a better fix than the env-vars anyhow so I'll come up with something. Check Arcan repo later today.

**Comment by deb75** [comment]
Thanks for taking care of my issues !

I also tried to change the terminal color palette as you advocated, there were `solarized` dark and white.
I tried both but nothing changed on the current terminal, not more on a new terminal : background color remained
black.

**Comment by letoram** [comment]
Thanks for being patient with trying things out.
I have a strong intuition for how this setup works, so quite blind to where people run into problems.
The terminal built-in palette thing was the old way of setting things, the dynamic swap is a recent addition / change (also the gruvbox-light included in durden actually lacked background colour, fixed).

But here, if I change the default terminal palette to gruvbox light and open new terminals, they will be light.

**Comment by deb75** [comment]
Hi,

I redownloaded `arcan/durden` and recompiled it.

The keyboard settings and color palette now work as expected ,except that I cannot get the € symbol (Alt Gr + e)

I still have some issues with the touchpad and the touchscreen. The touchpad is somewhat unresponsive, it is
difficult to make the pointer mode. Strangely it is easier to make it move with the touchscreen but the pointer does not
jump to the finger position, it just follows the finger movement with a different speed.

You talked about classifier, what is it exactly ?

Regards

**Comment by letoram** [comment]
You can probably remap it for durden alone, though it won't save non-arcan clients. (global/input/keyboard/map/bind_utf8).

The classifiers are sets of rules for how to interpret touch input per device. The default as far as I recall is for it to emulate a relative mouse. https://github.com/letoram/durden/tree/master/durden/input/classifiers

That folder is scanned on startup and mapped on touch devices to global/input/touch/<device name>/classifier

**Comment by deb75** [comment]
Thanks for your answeer.

I will try to fix my touchpad and touchscreen issues by writing classifiers.

They are applied depending on the label, right ?

How do I get the correct label for my devices ? `libinput list-devices`?

Regards

**Comment by letoram** [comment]
so there is not a definitive way to get this because .. linux - the matching is done by the matchstr (==) or matchflt (string.match) you can see the labels in global/input/all devices (each entry corresponds to  the detected device label)

**Comment by deb75** [comment]
Hi,

I managed to make something better by adjusting `devmaps/default.lua`.

For the touchscreen, I use `absmouse` as classifier. However, I noticed also `touch-fit` and `touch-scaled` 
classifiers in the dynamic menu. Should not these classifiers be more relevant for touch-screens/pads ?

I plan then to duplicate the `default.lua` to make custom settings for the touchscreen and the touchpad.
May I know in which units the `range = {}` settings has to be given ?

Regards

**Comment by letoram** [comment]
There isn't a 'works for everything' classifier - if the active client can handle touch input, then the touch- set of classifiers makes more sense: touch-fit if you want a 1:1 mapping between what you see on the screen and where you can touch (where the touch device and the screen are physically the same). The touch-scaled if you want to use the entire screen for the selected window which makes sense if you are doing precision-relative work (say a drawing tablet where the screen is detached).

If the active client cannot handle touch input, the mouse classifiers work as they emulate the mouse rather than act as a separate input device.

The range is device-dependent, it can be queried from the device itself but from the test set I have here they are not that accurate. You can see the values for your screen with evdev, the "autorange" just records the highest/lowest its seen, so when you sweep the outer ranges of your device it will "get it". All these feel parameters would work better as a runtime calibration tool, especially if you want the highest precision as that can change with ambient temperature, grounding environment (charger cable plugged in or not).
